<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8" 
    isELIgnored="false"  %>
 <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"  %>
<c:set var="contextPath"  value="${pageContext.request.contextPath}"  />

<%
  request.setCharacterEncoding("UTF-8");
%>    

<div
	id="monthlyView"
>
	<div
		id="monthlyView_header"
	>
		<div
			id="monthlyView_header_title"
		>
			${year}년 ${month }월
		</div>
		<div
			id="monthlyView_header_search"
		>
			<div	
				id="monthlyView_header_search_container"
			>
				<form
					action="${contextPath}/weeklyPlan/monthlyView.do"
					method="get"
					id="monthlyView_search"
				>
					 <div>
						<input 
							type="text" 
							placeholder="month"
							name="month"
							id="monthlyView_search_month"
						/>
					 </div>
					 <div>
						 <button
							 type="submit"
							 form="monthlyView_search"
							 id="monthlyView_search_month_button"
						 >
							<img 
								alt="검색"
								src="${contextPath}/resources/images/search-black-18dp.svg"
								class="icon"
							/>
						 </button>
					 </div>
				</form>
			</div>
			<div
				id="monthlyView_header_arrow"
			>
				<div
					id="monthlyView_header_arrow_left"
				>
					<img 
						alt="left" 
							src="${contextPath}/resources/images/arrow_left-black-18dp.svg"
						>
				</div>
				<div
					id="monthlyView_header_arrow_right"
				>
					<img 
						alt="right" 
						src="${contextPath}/resources/images/arrow_right-black-18dp.svg"
					>
				</div>	
			</div>
		</div>
	</div>
	<div
		id="monthlyView_body"
	>
		<div
			id="monthlyView_body_left"
		>
			<div
				class="monthlyView_body_left_header"
			>
				<div
					id="monthlyView_body_left_header_title"
				>
					Monthly Plan
				</div>
			</div>
			<div
				id="monthlyView_body_left_body"
			>
				<div
					class="monthlyView_body_left_padding"
				>
				</div>
				<div
					id="monthlyView_body_left_add"
				>
					<div
						id="monthlyView_body_left_add_button"
					>
						<img
							alt="add_button" 
							src="${contextPath }/resources/images/add-black-18dp.svg"
						>
					</div>
				</div>
			</div>
		</div>
		<div
			id="monthlyView_body_right"
		>
			<div
				class="monthlyView_body_right_padding"
			>
			</div>
		</div>
	</div>
</div>

<script src="${contextPath }/resources/javascript/baselayout/monthlyplan/monthlyPlanList.js"></script>